---
- name: Create user and force password change
  hosts: all
  become: yes

  vars:
    username: ansible
    user_password_hash: "$6$zMog7L8rldXyUPE6$If5ilN.7sro33LnVZXzeJ.2HO1Qd.ESvWM2HUq7YLM1Qb/sLFBjEZ0Pgi1W5CTR7n8eSU3lg1.7TVmVlSoeUo."

  tasks:

    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes
        password: "{{ user_password_hash }}"

    - name: Force password change on first login
      ansible.builtin.command:
        cmd: chage -d 0 {{ username }}

    - name: Add reconnect reminder
      ansible.builtin.lineinfile:
        path: "/home/{{ username }}/.bashrc"
        line: 'echo "Please reconnect your SSH session after changing your password."'
        create: yes
