---
- name: Check disk usage
  hosts: all

  tasks:

    - name: Show disk usage
      command: df -h
      register: disk_output

    - name: Print disk usage
      debug:
        var: disk_output.stdout_lines
